### PR TITLE
Show permission dialog to request contacts permission

### PR DESCRIPTION
**Pull request by jashasweejena**

### CODE REVIEW

**Comment by Bhavnaharitsa** [comment]
This permission dialog box will come when?

**Comment by Bhavnaharitsa** [comment]
and please resolve conflicts

**Comment by jashasweejena** [comment]
> This permission dialog box will come when?

It will come right after the app starts since I coded the functionality in onCreate(). If the permission is denied, it will ask for permission once again and it continues recursively.

**Comment by jashasweejena** [comment]
> and please resolve conflicts

Sure!

**Pull request merged**
